=== wanyonyi-dev/bookstore/bookstore.dtd
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, author, price, isbn, category, publication_year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT publication_year (#PCDATA)>
<!ATTLIST book category (children|fiction|non-fiction) #REQUIRED>

=== wanyonyi-dev/bookstore/bookstore.xml
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">
<bookstore>
    <book category="children">
        <title>Harry Potter and the Philosopher's Stone</title>
        <author>J.K. Rowling</author>
        <price>19.99</price>
        <isbn>978-0747532743</isbn>
        <category>children</category>
        <publication_year>1997</publication_year>
    </book>
    <book category="fiction">
        <title>The Great Gatsby</title>
        <author>F. Scott Fitzgerald</author>
        <price>15.99</price>
        <isbn>978-0743273565</isbn>
        <category>fiction</category>
        <publication_year>1925</publication_year>
    </book>
</bookstore>
